name: Build Unsigned iOS IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'v3.3.1'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install Dependencies
        run: flutter pub get

      - name: Build iOS App (No Codesign)
        run: flutter build ios --release --no-codesign

      - name: Packaging to IPA
        run: |
          mkdir -p Payload
          mv build/ios/iphoneos/Runner.app Payload/
          zip -r Conduit.ipa Payload

      - name: Upload Finished IPA
        uses: actions/upload-artifact@v4
        with:
          name: Conduit-Unsigned-IPA
          path: Conduit.ipa
